# Conhecendo a base de dados

## Importando os dados

In [12]:
import pandas as pd

In [13]:
dados = 'dados.csv'

dados = pd.read_csv(dados, sep=';')

# A função head() retorna as 5 primeiras linhas do dataframe
display(dados.head(1))

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0

In [14]:
# A função .tail() retorna as 5 últimas linhas do dataframe
display(dados.tail(1))

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [15]:
# type() retorna o tipo de dado
type(dados)

pandas.DataFrame

## Características gerais da base de dados

In [ ]:
# Explorando a quantidade de linhas e colunas

dados.shape # Retorna a quantidade de linhas e colunas do dataframe.

(32960, 9)

In [ ]:
dados.columns # Retorna uma tupla das colunas

Index(['Tipo', 'Bairro', 'Quartos', 'Vagas', 'Suites', 'Area', 'Valor',
       'Condominio', 'IPTU'],
      dtype='str')

In [ ]:
dados.info() # Retorna o tipo de dados e outros

<class 'pandas.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32960 non-null  str
 1   Bairro      32960 non-null  str
 2   Quartos     32960 non-null  int64
 3   Vagas       32960 non-null  int64
 4   Suites      32960 non-null  int64
 5   Area        32960 non-null  int64
 6   Valor       32943 non-null  float64
 7   Condominio  28867 non-null  float64
 8   IPTU        22723 non-null  float64
dtypes: float64(3), int64(4), str(2)
memory usage: 3.0 MB

In [ ]:
# Dados do tipo object são strings
# [ ] retorna dados no formato series

dados['Tipo'].head() # Tipo object são strings

   Quartos   Valor
0        1  1700.0
1        2  7000.0
2        0  5200.0
3        1   800.0
4        1   800.0

In [ ]:
dados[['Quartos','Valor']].head() # Quando adicionamos dois colchetes é possível retornar mais de uma coluna.

       Quartos   Valor
0            1  1700.0
1            2  7000.0
2            0  5200.0
3            1   800.0
4            1   800.0
...        ...     ...
32955        0   800.0
32956        3  1800.0
32957        2  1400.0
32958        2  3000.0
32959        0  6500.0

[32960 rows x 2 columns]

# Análise exploratória de dados

## Qual o valor médio de aluguel por tipo de imóvel?

## Removendo os imóveis comerciais

## Qual o percentual de cada tipo de imóvel na nossa base de dados?

### **Selecionando apenas os imóveis do tipo apartamento**

# Tratando e filtrando os dados

## Lidando com dados nulos

## Removendo registros

## Filtros

### **1. Apartamentos que possuem `1 quarto` e `aluguel menor que 1200`**

### **2. `Apartamentos` que possuem pelo menos `2 quartos`, `aluguel menor que 3000` e `area maior que 70`**

## Salvando os dados

# Manipulando os dados

## Criando colunas numéricas

## Criando colunas categóricas