#### Aula09 - Desafio: bora praticar?

In [18]:
import pandas as pd

dados = pd.read_csv('Arquivos_Aula/Aula_4_dados.csv',sep=';')

dados.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN

##### O time de ML chegou com algumas demandas de última hora para resolvermos nesse momento da análise exploratória. Essas demandas são:

##### 1) Calcular a média de quartos dos imóveis:

In [35]:
imoveis_comerciais = ['Conjunto Comercial/Sala', 

                      'Prédio Inteiro', 'Loja/Salão', 

                      'Galpão/Depósito/Armazém', 

                      'Casa Comercial', 'Terreno Padrão',

                      'Loja Shopping/ Ct Comercial',

                      'Box/Garagem', 'Chácara',

                      'Loteamento/Condomínio', 'Sítio',

                      'Pousada/Chalé', 'Hotel', 'Indústria']


df = dados.query('@imoveis_comerciais not in Tipo')

df['Tipo'].unique()

df_media_quartos = df.groupby('Tipo')[['Valor']].mean().sort_values('Valor')

df_media_quartos

                           Valor
Tipo
Quitinete            1246.840909
Casa de Vila         1574.369478
Studio               2400.000000
Loft                 2557.882353
Flat                 4546.189076
Apartamento          4744.614648
Casa                 6793.454922
Casa de Condomínio  11952.061245

##### 2) Conferir quantos bairros únicos existem na nossa base de dados;

In [38]:
df['Bairro'].unique()

<ArrowStringArray>
[         'Copacabana',     'Jardim Botânico',              'Centro',
        'Higienópolis',        'Vista Alegre',            'Cachambi',
     'Barra da Tijuca',               'Ramos',              'Grajaú',
 'Lins de Vasconcelos',
 ...
                'Tauá',             'Ribeira',    'Magalhães Bastos',
              'Cacuia',           'Bancários',          'Cavalcanti',
        'Rio da Prata',       'Cidade Jardim',         'Coelho Neto',
             'Grumari']
Length: 154, dtype: str

##### 3) Analisar quais bairros possuem a média de valor de aluguel mais elevadas;

##### 4) Criar um gráfico de barras horizontais que apresente os 5 bairros com as médias de valores de aluguel mais elevadas.