#####  Aula 04.6 Para saber mais: criando colunas

In [3]:
# Existem diversas maneiras de criar colunas em um DataFrame no Pandas. Alguns exemplos são:

# 1 - Atribuição direta de valores a uma nova coluna:

import pandas as pd

df = pd.DataFrame({
    'A':[1,2,3],
    'B':[4,5,6]
})

df['C'] = [7, 8, 9]

df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [4]:
# 2 - Criação de uma coluna a partir de operações entre outras colunas:

df = pd.DataFrame({
    'A':[1, 2, 3],
    'B':[4, 5, 6]
})

df['C'] = df['A'] + df['B']
df

   A  B  C
0  1  4  5
1  2  5  7
2  3  6  9

In [5]:
# 3 - Utilização do método assign() para criar uma nova coluna:

df = pd.DataFrame({
    'A':[1, 2, 3],
    'B':[4, 5, 6]
})

df = df.assign(C=[7, 8, 9])
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [7]:
# 4 - Utilização do método apply() para aplicar uma função a uma coluna existente e criar uma nova coluna:

df = pd.DataFrame({
    'A':[1, 2, 3],
    'B':[4, 5, 6]
})

df['C'] = df['A'].apply(lambda x: x * 2)
df

   A  B  C
0  1  4  2
1  2  5  4
2  3  6  6